### ISSUE TITLE
17.10RC1: mail template for "account-disabled-notification" is not available

### ISSUE THREAD

**Issue by gehlen** [joosth/workflow4people#38]
Login into workflow4people web interface 3 times with user "admin" and password "test", error message below is shown in workflow4people logging..
> | Error 2017-11-21 11:31:14,411 [notificationMailJmsListenerContainer-1] ERROR services.NotificationService  - NotificationService.mail(...) threw a NullPointerException. Error message: [Email template [account-disabled-notification] does not exist.].

Mail template for "account-disabled-notification" should be added by default..

**Comment by hwinwuzhere** [comment]
Correct! Will fix this issue ASAP.

**Comment by hwinwuzhere** [comment]
Issue has been resolved in the latest develop commit.
