### ISSUE TITLE
17.10RC1: generated GSP's are empty after using workflow wizard

### ISSUE THREAD

**Issue by gehlen** [joosth/workflow4people#40]
Create a workflow using the wizard..
At step 2, choose "Simple one step workflow"
At step 4, use name "test" and title "Test"

After completing all steps, the generated request / task / edit / show GSP's are empty:
![image](https://user-images.githubusercontent.com/432016/33071184-d7413760-ceba-11e7-9e1b-40dbb3bb1940.png)

**Comment by hwinwuzhere** [comment]
This issue has already been resolved and will soon be pushed to the develop branch.
