### ISSUE TITLE
17.11RC4: Error in logging after frontend login

### ISSUE THREAD

**Issue by gehlen** [joosth/workflow4people#42]
On a clean setup, login as "demo" in frontend.

Logging backend:
> [documentQueueHandleMessageJmsListenerContainer-1] ERROR services.PathService  - Exception while creating parent in new path :/users: Cannot get property 'id' on null object
> [documentQueueHandleMessageJmsListenerContainer-1] ERROR services.PathService  - Fallback to Folder XML

**Comment by hwinwuzhere** [comment]
This is actually an issue we've also encountered. We'll find a fix for this!

**Comment by hwinwuzhere** [comment]
This issue has been resolved and will be taken into the next release.
