### ISSUE TITLE
17.11RC4: Adhoc request dialog not showing up

### ISSUE THREAD

**Issue by gehlen** [joosth/workflow4people#43]
On a clean setup, login as "demo", start a new "Adhoc" form.

Page is reloading, so no dialog is opening.
When we look at the generated request.gsp, it's empty.

This issue is related to #40

**Comment by gehlen** [comment]
Same problem exists in frontend for:
- opening a user show dialog on the documentlist page;
- opening the "Edit user profile" dialog;

**Comment by hwinwuzhere** [comment]
When you're migrating from a previous Workflow4people instance, you have to reset the form templates for all forms. Do you have a setup with a static /var/opt/wfp/template directory, or do you have a symlink to the wfp/bootstrap-form-templates folder?

**Comment by gehlen** [comment]
My template folder was indeed older than the current 17.11RC4 one, my fault. It's working now. Sorry for the inconvenience.
I'll close this issue.
