### ISSUE TITLE
17.11RC4: data model FieldType drag&drop issue

### ISSUE THREAD

**Issue by gehlen** [joosth/workflow4people#44]
On a clean setup, create a FieldType named "test" with basetype "List".
Drag&drop the "Header" FIeldType onto this "test" FieldType, there's an error shown and nothing happened:

> java.lang.NullPointerException: Cannot get property 'field' on null object at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172) at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296) at org.workflow4people.services.DmeEventService.dragFieldTypeToFieldType(DmeEventService.groovy:83) ...

**Comment by hwinwuzhere** [comment]
I've encountered a similar problem with the copy/paste function in the DME. Certainly worth checking out.

**Comment by hwinwuzhere** [comment]
This issue has been resolved and will be taken into the next release.
